<%@ Page Language="C#" MasterPageFile="MasterPage.Master" AutoEventWireup="true" CodeBehind="QuestionXls.aspx.cs" Inherits="XueFuShop.Admin.QuestionXls" Title="无标题页" %>
<asp:Content ID="MasterContent" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
<div class="position"><img src="/Admin/Style/Images/PositionIcon.png"  alt=""/>试题导入</div>
<div class="add">		<%--<ul>		<li class="left">课程类别：</li>		<li class="right">
              &nbsp;<asp:DropDownList ID="_CateId" runat="server" OnSelectedIndexChanged="_CateId_SelectedIndexChanged" AutoPostBack="True">
              </asp:DropDownList></li>			</ul>	<ul>		<li class="left">课程名称：</li>		<li class="right">
              &nbsp;<asp:DropDownList ID="_CourseId" runat="server">
              </asp:DropDownList></li>	</ul>--%>	<ul>		<li class="left">课程名称：</li>		<li class="right"><asp:Label ID="CourseName" runat="server" Text="Label"></asp:Label></li>	</ul>	<ul id="fileout" runat="server">		<li class="left">导出试题数量：</li>		<li class="right"><asp:TextBox CssClass="input" ID="QuestionNum" runat="server">0</asp:TextBox> 默认为“0”时为导出全部试题</li>	</ul>	<ul id="filein" runat="server"><li class="left">文件路径：</li>		<li class="right"><asp:FileUpload ID="FilePath" CssClass="input" runat="server" Width="300px" /></li>
    </ul></div><div  id="ListShow" runat="server">    <table class="listTable" cellpadding="0">        <tr class="listTableHead">            <td>序号</td>	        <td>题目</td>	        <td>题型</td>	        <td>A</td>	        <td>B</td>	        <td>C</td>	        <td>D</td>	        <td>Answer</td>	                    </tr>    <asp:Repeater ID="RecordList" runat="server">	    <ItemTemplate>	             	    <tr class="listTableMain" onmousemove="changeColor(this,'#FFFDD7')" onmouseout="changeColor(this,'#FFF')">			        <td><%# Container.ItemIndex + 1%></td>			        <td><%# Eval("Question") %></td>			        <td><%# Eval("Style") %></td>			        <td><%# Eval("A") %></td>	                <td><%# Eval("B") %></td>	                <td><%# Eval("C") %></td>	                <td><%# Eval("D") %></td>			        <td><%# Eval("Answer") %></td>		        </tr>            </ItemTemplate>    </asp:Repeater>    </table></div><div class="action">    <asp:Button CssClass="button" ID="FileInButton" Text="导入试题" runat="server"  OnClick="FileInButton_Click" />    <asp:Button CssClass="button" ID="FileOutButton" Text="完整试题" runat="server"  OnClick="FileOutButton_Click" />    <asp:Button CssClass="button" ID="QuestionOutButton" Text="题目" runat="server" OnClick="QuestionOutButton_Click"/>    <asp:Button CssClass="button" ID="QuestionOk" Text="试题入库" runat="server" OnClick="QuestionOk_Click" Visible="False" /></div>
</asp:Content>
