<%@ Page Language="C#" MasterPageFile="MasterPage.Master" AutoEventWireup="true" CodeBehind="Questions.aspx.cs" Inherits="XueFuShop.Admin.Questions" Title="无标题页" %>
<%@ Import Namespace="XueFuShop.BLL" %><asp:Content ID="MasterContent" ContentPlaceHolderID="ContentPlaceHolder" runat="server"><div class="position"><img src="/Admin/Style/Images/PositionIcon.png"  alt=""/>试题列表</div>	<ul class="search">    <li>
        分类：<asp:DropDownList ID="SearchCategory" runat="server"></asp:DropDownList>
        课程名称：<XueFu:TextBox ID="SearchCourseName" CssClass="input" runat="server"/>
        试题名称：<XueFu:TextBox ID="SearchQuestionName" CssClass="input" runat="server"/>
        试题类型：<asp:DropDownList ID="SearchQuestionStyle" runat="server"></asp:DropDownList>        <asp:Button CssClass="button" ID="SearchButton" Text=" 搜 索 " runat="server"  OnClick="SearchButton_Click" />    </li></ul>
<table class="listTable" cellpadding="0">    <tr class="listTableHead">	    <td style="width:8%">选择</td>	    <td style="width:50%; text-align:left;text-indent:8px;">题目</td>	    <td style="width:18%">分类</td>	    <td style="width:12%">题型</td>        <td>管理</td>    </tr><asp:Repeater ID="RecordList" runat="server">	<ItemTemplate>	             	<tr class="listTableMain" onmousemove="changeColor(this,'#FFFDD7')" onmouseout="changeColor(this,'#FFF')">			    <td><input type="checkbox" name="SelectID" value="<%# Eval("QuestionId") %>" /></td>			    <td style="text-align:left;text-indent:8px;"><%# Eval("Question") %></td>			    <td><%# CourseBLL.ReadCourse(Convert.ToInt32(Eval("CateId"))).CourseName%></td>	            <td><%# EnumHelper.ReadEnumChineseName <QuestionType>(Convert.ToInt32(Eval("Style")))%></td><td>		    			       <%# updateQuestionPower ? "<a href=\"javascript:pop(\'QuestionAdd.aspx?ID=" + Eval("QuestionId") + "\',700,500,\'修改信息\',\'CompanyAdd" + Eval("QuestionId") + "\')\"><img src=\"Style/Images/edit.gif\" alt=\"修改信息\" title=\"修改信息\" /></a>" : ""%>			       <%# deleteQuestionPower ? " <a href=\'Questions.aspx?Action=Delete&ID=" + Eval("QuestionID") + "\' onclick=\"return check()\"><img src=\"Style/Images/delete.gif\" alt=\"删除\" title=\"删除\" /></a>" : ""%>			    </td>		    </tr>        </ItemTemplate></asp:Repeater></table><div class="listPage"><XueFu:CommonPager ID="MyPager" runat="server" /></div>
<div class="action">    <input type="button"  value=" 添 加 " class="button" onclick="pop('QuestionAdd.aspx',800,600,'用户添加','CompanyAdd')" id="Button1"/>    <asp:Button CssClass="button" ID="DeleteButton" Text=" 删 除 " OnClientClick="return checkSelect()" runat="server"  OnClick="DeleteButton_Click"/>    <input type="checkbox" name="All" onclick="selectAll(this)" />全选/取消
</div>
</asp:Content>
