<%@ Page Language="C#" MasterPageFile="MasterPage.Master" AutoEventWireup="true" CodeBehind="UserGradeAdd.aspx.cs" Inherits="XueFuShop.Admin.UserGradeAdd" %>
<asp:Content ID="MasterContent" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
<div class="position"><img src="Style/Images/PositionIcon.png"  alt=""/>用户等级<%=GetAddUpdate()%></div><div class="add">	<ul>		<li class="left">等级名称：</li>		<li class="right"><asp:TextBox ID="Name" CssClass="input" runat="server" Width="100px"></asp:TextBox>   <asp:RequiredFieldValidator
        ID="RequiredFieldValidator1" runat="server" ErrorMessage="不能为空" ControlToValidate="Name" Display="Dynamic"></asp:RequiredFieldValidator></li>		<li class="left">折扣：</li>		<li class="right"><asp:TextBox ID="Discount" CssClass="input" runat="server" HintInfo="如写入60表示6折" RequiredFieldType="金额" Width="100px"></asp:TextBox>   <asp:RequiredFieldValidator
        ID="RequiredFieldValidator2" runat="server" ErrorMessage="不能为空" ControlToValidate="Discount" Display="Dynamic"></asp:RequiredFieldValidator></li>	</ul>	<ul>		<li class="left">最低金额：</li>		<li class="right"><asp:TextBox ID="MinMoney" CssClass="input" runat="server" HintInfo="大于或者等于最低金额" RequiredFieldType="金额" Width="100px"></asp:TextBox>  <asp:RequiredFieldValidator
        ID="RequiredFieldValidator3" runat="server" ErrorMessage="不能为空" ControlToValidate="MinMoney" Display="Dynamic"></asp:RequiredFieldValidator></li>		<li class="left">最高金额：</li>		<li class="right"><asp:TextBox ID="MaxMoney" CssClass="input" runat="server" HintInfo="小于最高金额" RequiredFieldType="金额" Width="100px"></asp:TextBox>  <asp:RequiredFieldValidator
        ID="RequiredFieldValidator4" runat="server" ErrorMessage="不能为空" ControlToValidate="MaxMoney" Display="Dynamic"></asp:RequiredFieldValidator></li>	</ul>	
    <asp:TextBox ID="Hit" runat="server" Visible="False"></asp:TextBox></div><div class="action">    <asp:Button CssClass="button" ID="SubmitButton" Text=" 确 定 " runat="server"  OnClick="SubmitButton_Click" /></div>
</asp:Content>
